/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rogerio.app;

import br.com.rogerio.model.Carro;
import br.com.rogerio.model.FabricaDeCarros;
import br.com.rogerio.enumeration.EnumCarros;
import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class FabricaView extends javax.swing.JFrame {

    FabricaDeCarros fabrica;

    /**
     * Creates new form FabricaView
     */
    public FabricaView() {
        initComponents();

        //Este linha baixo faz a quebra de linha ao final do tamanho do textArea
        this.jTextAreaSaidaDosObjetos.setLineWrap(true);

        jComboBoxObjetos.removeAllItems();
        jComboBoxObjetos.addItem("< Selecione aqui seu objeto >");
        for (EnumCarros carros : EnumCarros.values()) {
            jComboBoxObjetos.addItem(carros.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFacTory = new javax.swing.JPanel();
        jComboBoxObjetos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaidaDosObjetos = new javax.swing.JTextArea();
        jButtonFabricarObjeto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fabrica de Objetos");
        setResizable(false);

        jComboBoxObjetos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Selecione o seu objeto >" }));

        jTextAreaSaidaDosObjetos.setColumns(20);
        jTextAreaSaidaDosObjetos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaidaDosObjetos);

        jButtonFabricarObjeto.setText("Fabricar o objeto selecionado");
        jButtonFabricarObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFabricarObjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFacToryLayout = new javax.swing.GroupLayout(jPanelFacTory);
        jPanelFacTory.setLayout(jPanelFacToryLayout);
        jPanelFacToryLayout.setHorizontalGroup(
            jPanelFacToryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFacToryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(jPanelFacToryLayout.createSequentialGroup()
                .addGroup(jPanelFacToryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFacToryLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFacToryLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jButtonFabricarObjeto)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelFacToryLayout.setVerticalGroup(
            jPanelFacToryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFacToryLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jComboBoxObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonFabricarObjeto)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFacTory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFacTory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFabricarObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFabricarObjetoActionPerformed
        try {
            fabrica = FabricaDeCarros.getInstance();
            Carro objeto = fabrica.getCarro(jComboBoxObjetos.getSelectedItem().toString());
            jTextAreaSaidaDosObjetos.setText(fabrica.imprimir(objeto));
            jComboBoxObjetos.setSelectedIndex(0);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
        
    }//GEN-LAST:event_jButtonFabricarObjetoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FabricaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FabricaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FabricaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FabricaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FabricaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFabricarObjeto;
    private javax.swing.JComboBox<String> jComboBoxObjetos;
    private javax.swing.JPanel jPanelFacTory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSaidaDosObjetos;
    // End of variables declaration//GEN-END:variables
}
